### ISSUE TITLE
There is a problem with the test set

### ISSUE THREAD

**Issue by King-test789** [poojithabhat/Insurance-Cross-Sales-classification-Capstone#1]
Dude, good job, but I don't think you should do SMOTE sampling first and then be dividing the dataset. Because it will lead to augmented data in the test set.

**Comment by Coder-Liuu** [comment]
@King-test789 Just uploaded the wrong account, this is my account  :sweat_smile:

**Comment by poojithabhat** [comment]
Thanks a lot of pointing out the problem! 
I agree with the issue you have pointed out and it makes logical sense.
I am beginner at ML and thanks to people like you, I am able to identify my mistakes and get more clarity! 
Will work on rectifying it.

**Comment by poojithabhat** [comment]
> @King-test789 Just uploaded the wrong account, this is my account

Thanks a lot of pointing out the problem! 
I agree with the issue you have pointed out and it makes logical sense.
I am beginner at ML and thanks to people like you, I am able to identify my mistakes and get more clarity! 
Will work on rectifying it.

**Comment by Coder-Liuu** [comment]
I am glad to get your reply and I am sure you will become a master of ML. (Please pardon my poor English)
